version: '3'

services:
  portfolio-backend:
    image: maxlehmann01/portfolio-backend:latest
    container_name: portfolio-backend
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ~/deployment/portfolio/backend/.env:/usr/src/app/.env
      - ~/deployment/portfolio/backend/logs/:/usr/src/app/logs
    environment:
      - TZ=Europe/Berlin