version: '3'

services:
  portfolio-backend:
    image: maxlehmann01/portfolio-backend:production
    container_name:  production.portfolio-backend
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ~/deployment/portfolio/backend/.env:/usr/src/app/.env
    environment:
      - TZ=Europe/Berlin