version: '3'

services:
  portfolio-backend:
    image: docker.5vv5404h4uiv.com/portfolio-backend:latest
    container_name: portfolio-backend
    ports:
      - "15023:3000"
    restart: always
    volumes:
      - /root/portfolio/backend/.env:/usr/src/app/.env
      - /root/portfolio/backend/logs/:/usr/src/app/logs
    environment:
      - TZ=Europe/Berlin
    networks:
      - mongo

networks:
  mongo:
    external: true