name: Docker-Build-And-Deploy

on:
  push:
    branches:
      - main

jobs:
  build-image:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with: 
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY_USER }}/portfolio-backend:production
    
  deploy-image:
    needs: build-image
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy docker-compose.yml
        run: cp ./docker/docker-compose.yml ~/deployment/portfolio/backend

      - name: Run docker-compose.yml
        run: cd ~/deployment/portfolio/backend && docker-compose pull && docker-compose up -d