name: Docker-Build-And-Deploy

on:
  push:
    branches:
      - main

jobs:
  build-image:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with: 
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: portfolio-backend:production
    
  deploy-image:
    needs: build-image
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy docker-Compose.yml
        run: scp -o StrictHostKeyChecking=no ./docker/docker-compose.yml ${{ secrets.SSH_USER }}@${{ secrets.SSH_IP }}:~/deployment/portfolio/backend

      - name: Run docker-compose.yml
        run: ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_IP }} "cd ~/deployment/portfolio/backend && docker-compose pull && docker-compose up -d"